name: Manage PR Labels
description: Add or remove PR labels.

inputs:
  token:
    type: string
    required: false
    description: Token used to execute the operation.
    default: ${{ github.token }}
  operation:
    type: choice
    required: true
    description: What operation would you like to perform?
    options:
      - add
      - remove
  label:
    type: string
    required: true
    description: What label would you like to add or remove?

runs:
  using: 'composite'
  steps:
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: console.log(context)

    - name: Add Label
      if: ${{ inputs.operation == 'add' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token || inputs.token }}
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ["${{ inputs.label }}"],
          })

    - name: Remove Label
      if: ${{ inputs.operation == 'remove' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token || inputs.token }}
        script: |
          github.rest.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: "${{ inputs.label }}",
          })