name: Manage PR Labels
description: Add or remove PR labels.

inputs:
  token:
    type: string
    required: false
    description: Token used to execute the operation.
    default: ${{ github.token }}
  operation:
    type: choice
    required: true
    description: What operation would you like to perform?
    options:
      - add
      - remove
  label:
    type: string
    required: true
    description: What label would you like to add or remove?
  pull-request-number:
    type: string
    required: false
    description: Which pull request would you like to perform this operation on?
    default: ${{ github.event.pull_request.number }}

runs:
  using: 'composite'
  steps:
    - name: Add / Add Label
      if: ${{ inputs.operation == 'add' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          github.rest.issues.addLabels({
            issue_number: ${{ inputs.pull-request-number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: [${{ inputs.label }}],
          })

    - name: Remove / Check if label exists
      uses: paul1k/check-pr-labels@v1.0.0
      if: ${{ inputs.operation == 'remove' }}
      id: check_pr_labels
      with:
        github-token: ${{ inputs.token }}
        pull-number: ${{ inputs.pull-request-number }}
        labels: '[${{ inputs.label }}]'

    - shell: bash
      run: echo "${{ steps.check_pr_labels.outputs.result }}"

    - name: Remove / Remove label if it exists
      if: ${{ inputs.operation == 'remove' && steps.check_pr_labels.outputs.result == 'true' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          github.rest.issues.removeLabel({
            issue_number: ${{ inputs.pull-request-number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: ${{ inputs.label }},
          })

