name: On PR to Main

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  trigger-e2e-tests:
    name: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: 293149
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Add label
        uses: ./.github/actions/manage-labels.yml
        with:
          token: ${{ steps.get_installation_token.outputs.token }}
          operation: add
          label: "e2e tests passed"

      # - name: Start a check run for the E2E tests
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ steps.get_installation_token.outputs.token }}
      #     script: |
      #       github.rest.checks.create({
      #         owner: "aryella-lacerda",
      #         repo: "ci-testing",
      #         head_sha: "${{ github.event.pull_request.head.sha }}",
      #         name: "E2E Tests - Staging",
      #         status: "queued"
      #       })

      # - name: Trigger Workflow
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ steps.get_installation_token.outputs.token }}
      #     script: |
      #       github.rest.actions.createWorkflowDispatch({
      #         owner: "aryella-lacerda",
      #         repo: "ci-testing-e2e",
      #         workflow_id: "run-e2e.yml",
      #         ref: "main",
      #         inputs: {
      #           "pull_request_sha": "${{ github.event.pull_request.head.sha }}",
      #         }
      #       })
