name: On PR to Main

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Head ref: $GITHUB_HEAD_REF"
          echo "Just ref: $REF"

      - run: echo "${{ toJSON(github) }}"

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          initial-status: in_progress
          environment: update

      - name: Update deployment status
        if: always()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: ${{ job.status }}