name: On Push to Main

on:
  push:
    branches:
      - 'main'

env:
  COMMIT: ${{ github.event.commits[0].message }}

jobs:
  on-push-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Other
        run: |
          echo '${{ toJSON(github) }}'

      - run: |
          echo "$GITHUB_HEAD_REF 
            | $REF 
            | ${{ github.event.pull_request.head.ref }} 
            | ${{ github.head_ref }}
            | ${{ github.ref }}"

