name: On PR Label

on:
  pull_request:
    types:
      - labeled
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: 293149
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check that PR has necessary labels
        uses: paul1k/check-pr-labels@v1.0.0
        id: check_pr_labels
        with:
          github-token: ${{ steps.get_installation_token.outputs.token }}
          pull-number: ${{ github.event.pull_request.number }}
          labels: '["e2e tests passed", "deployments succeeded"]'

      - name: Merge to Master
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        run: echo "Time to Merge to Master"