name: On PR to Main

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Head ref: $GITHUB_HEAD_REF"
          echo "Just ref: $REF"
