name: On PR to Main

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  on-pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "Head ref: $GITHUB_HEAD_REF"
          echo "Just ref: $REF"

      - run: |
          echo "$GITHUB_HEAD_REF 
            | $REF 
            | ${{ github.ref_name }}
            | ${{ github.event.pull_request.head.ref }} 
            | ${{ github.head_ref }}
            | ${{ github.ref }}"

      - run: echo "${{ toJSON(github) }}"

      - run: yarn test --coverage

      - uses: jgillick/test-coverage-reporter@v1.0.14
        with:
          coverage-file: coverage/coverage-final.json
          access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
