name: On PR to Main

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  on-pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "Head ref: $GITHUB_HEAD_REF"
          echo "Just ref: $REF"

      - run: |
          echo "$GITHUB_HEAD_REF 
            | $REF 
            | ${{ github.ref_name }}
            | ${{ github.event.pull_request.head.ref }} 
            | ${{ github.head_ref }}
            | ${{ github.ref }}"

      - run: echo "${{ toJSON(github) }}"

      - run: |
          yarn
          git fetch origin

          git switch ${{ github.event.pull_request.base.ref }}
          yarn install --force
          yarn test --coverage --coverageDirectory="base-branch/coverage"

          git switch --detach -
          yarn install --force
          yarn test --coverage

      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: 293149
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: jgillick/test-coverage-reporter@v1.0.14
        with:
          base-coverage-file: base-branch/coverage/coverage-final.json
          coverage-file: coverage/coverage-final.json
          access-token: ${{ steps.get_installation_token.outputs.token }}
