name: On PR Review

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Head ref: $GITHUB_HEAD_REF"
          echo "Just ref: $REF"

