name: On Checks Passed

on:
  push:
    branches:
      - 'main'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  job4:
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.*.result }}      
      - name: dump needs context
        env:
          GITHUB_CONTEXT: ${{ toJson(needs.*.result) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          echo ${{ 
            !contains(needs.*.result, 'failure') && 
            !contains(needs.*.result, 'cancelled') && 
            !contains(needs.*.result, 'skipped') }}