name: Test

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Change version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '2.3.8'

      - name: Test commit
        run: |
          git config --global user.email "aryella.lacerda@gmail.com"
          git config --global user.name "Aryella Lacerda"
          git add .
          git commit -m "ci: test if commit & push works on ci" --no-verify
          git push

