name: On PR Updated

on:
  push:
    branches:
      - 'main'
      - 'aryella/**'

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
