name: Experiment

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Start a check run for the E2E tests
        uses: LouisBrunner/checks-action@v1.3.1
        with:
          sha: ${{ github.sha }}
          token: ${{ github.token }}
          name: Test XYZ
          status: in_progress

      - name: Trigger the other workflow
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/aryella-lacerda/ci-testing/actions/workflows/test.yml/dispatches \
          -d '{"ref": "aryella/a"}'

      - name: Watch the test run?
        uses: LouisBrunner/checks-action@v1.6.0
        if: always()
        with:
          token: ${{ github.token }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"${{ steps.test.outputs.summary }}"}