name: On Checks Passed

on:
  push:
    branches:
      - 'main'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  job4:
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.*.result }}