name: Test

on:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Change version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '2.3.7'

      - name: Test commit
        run: |
          git config --global user.email "ci@kasta.io"
          git config --global user.name "CI"
          git add .
          git commit -m "ci: test if commit & push works on ci" --no-verify
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
