name: Test

on:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Echo ref
        run: |
          echo ${{ github.event.head.ref }}
          echo ${{ github.event.base.ref }}