name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ github.ref }}
          echo ${{ toJson(github) }}

      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
