name: Trigger

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trigger-e2e-tests:
    name: Trigger E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ github.sha }}

      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: 293149
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Start a check run for the E2E tests
        uses: LouisBrunner/checks-action@v1.3.1
        with:
          sha: ${{ github.sha }}
          token: ${{ steps.get_installation_token.outputs.token }}
          name: E2E Tests - Staging
          status: in_progress

      - name: Trigger E2E Tests
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/aryella-lacerda/ci-testing-e2e/actions/workflows/run-e2e.yml/dispatches \
          -d '{"ref": "main"}'